version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - attach_workspace:
          at: .
      - run: pip3 install ansible boto boto3
      - add_ssh_keys:
         fingerprints:
          - "cf:68:bf:6a:5b:15:96:1c:54:ed:06:60:52:d2:ac:1d"
      - run: echo $PEM_FILE | sed 's/<CRLF>/\n/g' > keypass.pem
      - run: chmod 400 keypass.pem
      - run: echo $VAULT_PASS > .vault_pass.txt
      - run:
         command: ansible-playbook ansible/ec2_deploy.yml --user ubuntu --key-file keypass.pem --vault-pass-file .vault_pass.txt
         environment:
            ANSIBLE_HOST_KEY_CHECKING: False 
workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
            - build
         filters:
            branches:
               only: master
