- name: Terminate instances 
  hosts: localhost
  connection: local
  
  tasks:
    - name: Kill all eshop instances 
      ec2:
        instance_type: t2.small
        image: ami-085925f297f89fce1
        region: us-east-1
        key_name: keypass
        vpc_subnet_id: subnet-27048278
        assign_public_ip: yes
        wait: yes
        group: eshop
        count_tag: 
          Name: eshop
        instance_tags:
          Name: eshop
        aws_access_key: "{{access_key}}"
        aws_secret_key: "{{secret_key}}"
        security_token: "{{session_token}}"
        exact_count: 0
      register: ec2